name: create-pr-action
description: GitHub Action for creating PR

inputs:
  branch:
    description: Branch name of PR.
    required: true
  token:
    description: >
      GitHub token for creating PR.

      If not set this option, the GITHUB_TOKEN environment variable will be used.
    required: false

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
