name: Create GitHub Release based on changelog
description: GitHub Action for creating GitHub Releases based on changelog

inputs:
  changelog:
    description: Path to changelog
    required: false
    default: 'CHANGELOG.md'

runs:
  using: node12
  main: main.js
