name: Create GitHub Release
description: GitHub Action for creating GitHub Releases

inputs:
  changelog:
    description: Path to changelog
    required: false
    default: 'CHANGELOG.md'

runs:
  using: node12
  main: main.js
