name: Deploy GitHub Pages
description: GitHub Action for deploying GitHub Pages

inputs:
  deploy_dir:
    description: Directory to deploy
    required: true
  token:
    description: >
      GitHub token for creating GitHub Releases.

      If not set this option, the GITHUB_TOKEN environment variable will be used.
    required: false

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/main.sh
      shell: bash
