name: install-rust
description: GitHub Action for installing Rust toolchain

inputs:
  toolchain:
    description: Default toolchain to install
    required: false
    default: stable
  component:
    description: Components to add (comma-separated)
    required: false
  target:
    description: Targets to add (comma-separated)
    required: false

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
      shell: bash
      env:
        INPUT_TOOLCHAIN: ${{ inputs.toolchain }}
        INPUT_COMPONENT: ${{ inputs.component }}
        INPUT_TARGET: ${{ inputs.target }}
