name: Install Rust toolchain
description: GitHub Action for installing Rust toolchain

inputs:
  toolchain:
    description: Default toolchain to install, default is nightly
    required: false
    default: 'nightly'
  component:
    description: Components to add (comma-separated), default is empty
    required: false
  target:
    description: Targets to add (comma-separated), default is empty
    required: false

runs:
  using: node12
  main: main.js
