name: free-device-space
description: GitHub Action for freeing device space.

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
      shell: bash
    - run: df -h
      shell: bash
