name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: ./.github/workflows/tidy.yml
    permissions:
      security-events: write # for github/codeql-action/*

  free-device-space:
    needs: tidy
    strategy:
      fail-fast: false
      matrix:
        os:
          # NB: Sync list with https://github.com/taiki-e/checkout-action/blob/HEAD/.github/workflows/ci.yml
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-slim
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - windows-2022
          - windows-2025
          - windows-11-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - run: tools/print-dir-size.sh
      - uses: ./free-device-space
      - run: tools/print-dir-size.sh

  install-rust:
    needs: tidy
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-slim
          - macos-latest
          - windows-latest
          - windows-11-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: ./install-rust
        with:
          toolchain: nightly
          component: rustfmt,clippy
          target: x86_64-unknown-linux-musl,i686-unknown-linux-gnu
      - run: |
          rustc -Vv
          rustup -V
          cargo -Vv
          rustfmt -V
          cargo clippy -V
          rustup component list
          rustup target list

  setup-docker:
    needs: tidy
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: ./setup-docker

  cspell-dict:
    needs: tidy
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      # min-release-age and allow-git requires npm 11.10+
      - run: npm --version
      - run: sudo npm install --ignore-scripts=true --location=global npm@11.11.0
      - run: tools/cspell-dict.sh clean
      - run: git add -N . && git -c color.ui=always diff --exit-code
