# Build Rust binaries based on release workflow.
#
# There is no stability guarantee for this workflow, since it's supposed to only be
# used in infra managed by us.
#
# Usage:
#
# ```yaml
#   release-dry-run:
#     uses: taiki-e/github-actions/.github/workflows/release-dry-run.yml@main
# ```
#
# See "on.workflow_call.inputs" below for input options.

permissions: {}

on:
  workflow_call:
    inputs:
      rust:
        required: false
        type: string
        default: stable
      workflow:
        required: false
        type: string
        default: .github/workflows/release.yml
      job:
        required: false
        type: string
        default: release

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  # Reusable workflows cannot inherit environment variables.
  ATOMIC_MAYBE_UNINIT_DENY_WARNINGS: 1
  CARGO_HACK_DENY_WARNINGS: 1
  CARGO_LLVM_COV_DENY_WARNINGS: 1
  CARGO_MINIMAL_VERSIONS_DENY_WARNINGS: 1
  CARGO_NO_DEV_DEPS_DENY_WARNINGS: 1
  CONST_FN_DENY_WARNINGS: 1
  PORTABLE_ATOMIC_DENY_WARNINGS: 1
  SEMIHOSTING_DENY_WARNINGS: 1

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  prepare:
    runs-on: ubuntu-slim
    timeout-minutes: 15 # Max execution time of ubuntu-slim runner.
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - name: Prepare
        id: prepare
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          bail() {
            printf '::error::%s\n' "$*"
            exit 1
          }
          normalize_comma_or_space_separated() {
            # Normalize whitespace characters into space because it's hard to handle single input contains lines with POSIX sed alone.
            local list="${1//[$'\r\n\t']/ }"
            if [[ "${list}" == *","* ]]; then
              # If a comma is contained, consider it is a comma-separated list.
              # Drop leading and trailing whitespaces in each element.
              sed -E 's/ *, */,/g; s/^.//; s/,,$/,/' <<<",${list},"
            else
              # Otherwise, consider it is a whitespace-separated list.
              # Convert whitespace characters into comma.
              sed -E 's/ +/,/g; s/^.//' <<<" ${list} "
            fi
          }
          python3 -m venv ~/venv
          ~/venv/bin/pip --version
          # --uploaded-prior-to with duration in days requires pip 26.1.
          ~/venv/bin/pip install --upgrade pip
          ~/venv/bin/pip install --uploaded-prior-to=P14D yq
          yq() { ~/venv/bin/yq "$@"; }
          job=$(yq -c ".jobs.\"${INPUT_JOB}\"" "${INPUT_WORKFLOW}")
          bin=$(jq -r '.with."bin"' <<<"${job}")
          bin_target=$(jq -r '.with."bin-target"' <<<"${job}")
          if [[ "${bin}" == "null" ]]; then
            bail "'.jobs.${INPUT_JOB}.with.bin' of ${INPUT_WORKFLOW} must set"
          fi
          if [[ "${bin_target}" == "null" ]]; then
            bail "'.jobs.${INPUT_JOB}.with.bin-target' of ${INPUT_WORKFLOW} must set"
          fi
          matrix=''
          while read -rd, target; do
            matrix+=',{"target":"'"${target}"'","os":"'
            case "${target}" in
              *-linux-gnu*) matrix+=ubuntu-22.04 ;;
              *-apple-*) matrix+=macos-14 ;;
              *-windows-*) matrix+=windows-2022 ;;
              *) matrix+=ubuntu-24.04 ;;
            esac
            matrix+='"}'
          done < <(normalize_comma_or_space_separated "${bin_target}")
          printf 'matrix=%s\n' "{\"include\":[${matrix#,}]}" >>"${GITHUB_OUTPUT}"
          printf 'bin=%s\n' "${bin}" >>"${GITHUB_OUTPUT}"
        env:
          INPUT_JOB: ${{ inputs.job }}
          INPUT_WORKFLOW: ${{ inputs.workflow }}
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
      bin: ${{ steps.prepare.outputs.bin }}

  build:
    needs: prepare
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/github-actions/install-rust@68753a4331ec78cb842512fd16ae32da0c066e31 # main # zizmor: ignore[stale-action-refs]
        with:
          toolchain: ${{ inputs.rust }}
      - uses: taiki-e/setup-cross-toolchain-action@129361238c06ff2cc1c4ca5c5d2217af441ffdf6 # v1.40.1
        with:
          target: ${{ matrix.target }}
          runner: none
      - run: printf 'RUSTFLAGS=%s\n' "${RUSTFLAGS} -C target-feature=+crt-static" >>"${GITHUB_ENV}"
        if: contains(matrix.target, '-windows-msvc')
      - run: printf 'RUSTFLAGS=%s\n' "${RUSTFLAGS} -C target-feature=+crt-static -C link-self-contained=yes" >>"${GITHUB_ENV}"
        if: contains(matrix.target, '-linux-musl')
      # https://doc.rust-lang.org/rustc/platform-support.html
      - run: printf 'MACOSX_DEPLOYMENT_TARGET=10.12\n' >>"${GITHUB_ENV}"
        if: matrix.target == 'x86_64-apple-darwin'
      - run: printf 'MACOSX_DEPLOYMENT_TARGET=11.0\n' >>"${GITHUB_ENV}"
        if: matrix.target == 'aarch64-apple-darwin' || matrix.target == 'universal-apple-darwin'
      - id: build
        uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6 # v1.30.2
        with:
          dry-run: true
          bin: ${{ needs.prepare.outputs.bin }}
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          ref: refs/tags/dummy
      # For debugging
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.target }}
          path: ${{ steps.build.outputs.archive }}.*
