# Create and push the release commit and tag, publish crates, create GitHub release, and optionally upload binaries.
#
# There is no stability guarantee for this workflow, since it's supposed to only be
# used in infra managed by us.
#
# Note: This uses token-based publish for initial publish which Trusted Publishing doesn't work.
# Otherwise Trusted Publishing is used.
#
# Setup (common):
#
# 1. Visit https://github.com/settings/personal-access-tokens/new
#    and create an PAT with "Read and write" permission on "Contents"
#    for the target repository.
#
# 2. Visit https://github.com/<owner>/<repo>/settings/environments
#    and create "release" environment,
#    and set "Deployment protection rules" as needed (recommended).
#
#    Then create a environment secret named "PUSH_TOKEN"
#    with the API token created above.
#
# 3. If only selected actions are allowed,
#    Visit https://github.com/<owner>/<repo>/settings/actions
#    and add the followings to allowed actions:
#
#    actions/attest@*,
#    rust-lang/crates-io-auth-action@*,
#    taiki-e/*,
#
# Setup (initial publish):
#
# 1. Visit https://crates.io/settings/tokens
#    and create an API token with "publish-new" scope.
#
# 2. Visit https://github.com/<owner>/<repo>/settings/environments
#    and create a environment secret named "CARGO_REGISTRY_TOKEN"
#    with the API token created above.
#
# Setup (non-initial publish):
#
# 1. Visit https://crates.io/crates/<crate-name>/settings
#    and add Trusted Publishing setting like the following,
#    and enable "Require trusted publishing for all new versions" as needed (recommended).
#
#    Repository: <owner>/<repo>
#    Workflow: release.yml
#    Environment: release
#
# 2. If you used token-based publish for initial publish,
#    remove the API token on crates.io and the corresponding secret.
#
# Usage:
#
# (Please fill `<owner>` with the actual repository owner name.)
#
# ```yaml
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: Version to be increased
#         required: true
#         type: choice
#         options:
#           - patch
#           - minor
#           - major
#
#   publish:
#     if: github.repository_owner == '<owner>'
#     uses: taiki-e/github-actions/.github/workflows/rust-release.yml@main
#     permissions:
#       contents: write # for taiki-e/create-gh-release-action
#       id-token: write # for rust-lang/crates-io-auth-action
#       attestations: write # unused (used when options for uploading binaries are set)
#     secrets:
#       PUSH_TOKEN_APP_CLIENT_ID: ${{ secrets.PUSH_TOKEN_APP_CLIENT_ID }}
#       PUSH_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PUSH_TOKEN_APP_PRIVATE_KEY }}
#     with:
#       version: ${{ inputs.version }}
# ```
#
# Or:
#
# ```yaml
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: Version to be published
#         required: true
#         type: string
#
#   publish:
#     if: github.repository_owner == '<owner>'
#     uses: taiki-e/github-actions/.github/workflows/rust-release.yml@main
#     permissions:
#       contents: write # for taiki-e/create-gh-release-action
#       id-token: write # for rust-lang/crates-io-auth-action
#       attestations: write # unused (used when options for uploading binaries are set)
#     secrets:
#       PUSH_TOKEN_APP_CLIENT_ID: ${{ secrets.PUSH_TOKEN_APP_CLIENT_ID }}
#       PUSH_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PUSH_TOKEN_APP_PRIVATE_KEY }}
#     with:
#       version: ${{ inputs.version }}
# ```
#
# To upload binaries, you also need to set bin and bin-target:
#
# ```yaml
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: Version to be published
#         required: true
#         type: string
#
#   publish:
#     if: github.repository_owner == '<owner>'
#     uses: taiki-e/github-actions/.github/workflows/rust-release.yml@main
#     permissions:
#       contents: write # for taiki-e/create-gh-release-action / taiki-e/upload-rust-binary-action
#       id-token: write # for rust-lang/crates-io-auth-action / actions/attest
#       attestations: write # for actions/attest
#     secrets:
#       PUSH_TOKEN_APP_CLIENT_ID: ${{ secrets.PUSH_TOKEN_APP_CLIENT_ID }}
#       PUSH_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PUSH_TOKEN_APP_PRIVATE_KEY }}
#     with:
#       version: ${{ inputs.version }}
#       bin: <bin_name>
#       bin-target: |
#         x86_64-unknown-linux-gnu
#         x86_64-unknown-linux-musl
#         x86_64-apple-darwin
#         x86_64-pc-windows-msvc
# ```
#
# See "on.workflow_call.inputs" below for input options.

# TODO: Remove token-based one by requiring publish of 0.0.0 version on crates.io?

permissions: {}

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      tag-prefix:
        required: false
        type: string
        default: v
      rust:
        required: false
        type: string
        default: stable
      target:
        required: false
        type: string
      args:
        required: false
        type: string
      package:
        required: false
        type: string
      workspace:
        required: false
        type: boolean
        default: false
      changelog:
        required: false
        type: string
        default: CHANGELOG.md
      title:
        required: false
        type: string
        default: $version
      branch:
        required: false
        type: string
        default: main
      prefix:
        required: false
        type: string
      commit-prefix:
        required: false
        type: string
      bin:
        required: false
        type: string
      bin-target:
        required: false
        type: string
    secrets:
      PUSH_TOKEN_APP_CLIENT_ID:
        required: true
      PUSH_TOKEN_APP_PRIVATE_KEY:
        required: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  prepare:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/install-action@b8cecb83565409bcc297b2df6e77f030b2a468d5 # v2.82.0
        with:
          tool: rust@${{ inputs.rust }}+${{ inputs.target }},parse-changelog
          fallback: none
      - id: check
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          bail() {
            printf '::error::%s\n' "$*"
            exit 1
          }
          normalize_comma_or_space_separated() {
            # Normalize whitespace characters into space because it's hard to handle single input contains lines with POSIX sed alone.
            local list="${1//[$'\r\n\t']/ }"
            if [[ "${list}" == *","* ]]; then
              # If a comma is contained, consider it is a comma-separated list.
              # Drop leading and trailing whitespaces in each element.
              sed -E 's/ *, */,/g; s/^.//; s/,,$/,/' <<<",${list},"
            else
              # Otherwise, consider it is a whitespace-separated list.
              # Convert whitespace characters into comma.
              sed -E 's/ +/,/g; s/^.//' <<<" ${list} "
            fi
          }

          git() { command git -c core.fsmonitor=false "$@"; }
          git config user.name 'Taiki Endo'
          git config user.email 'te316e89@gmail.com'

          # shellcheck disable=SC2153
          version="${VERSION}"
          printf 'version(input): %s\n' "${version}"
          # shellcheck disable=SC2153
          tag_prefix="${TAG_PREFIX}"
          printf 'tag_prefix: %s\n' "${tag_prefix}"
          # shellcheck disable=SC2153
          changelog="${CHANGELOG}"
          printf 'changelog: %s\n' "${changelog}"

          # Get the current date.
          release_date=$(date -u '+%Y-%m-%d')
          printf 'release-date: %s\n' "${release_date}"
          printf 'release-date=%s\n' "${release_date}" >>"${GITHUB_OUTPUT}"

          # Get the current revision.
          rev=$(git rev-parse HEAD)
          printf 'rev: %s\n' "${rev}"
          printf 'rev=%s\n' "${rev}" >>"${GITHUB_OUTPUT}"

          # Get the previous version.
          metadata=$(cargo metadata --format-version=1 --no-deps)
          prev_version=''
          public_packages=''
          # Publishing is unrestricted if null, and forbidden if an empty array.
          # TODO: this assumes --workspace, but should respect default and package input option
          for pkg in $(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [])' <<<"${metadata}"); do
            eval "$(jq -r '@sh "name=\(.name) ACTUAL_VERSION=\(.version) manifest_path=\(.manifest_path)"' <<<"${pkg}")"
            public_packages+="${name}:${manifest_path},"
            if [[ -z "${prev_version}" ]]; then
              prev_version="${ACTUAL_VERSION}"
            fi
            # Make sure that the version number of all publishable workspace members matches.
            if [[ "${ACTUAL_VERSION}" != "${prev_version}" ]]; then
              bail "publishable workspace members must be version '${prev_version}', but package '${name}' is version '${ACTUAL_VERSION}'"
            fi
            # Make sure that the version marker is available.
            if ! grep -Eq "^version = \"${prev_version}\" #publish:version" "${manifest_path}"; then
              bail "not found '#publish:version' in version in ${manifest_path}"
            fi
          done
          printf 'prev-version: %s\n' "${prev_version}"
          printf 'prev-version=%s\n' "${prev_version}" >>"${GITHUB_OUTPUT}"
          printf 'public-packages: %s\n' "${public_packages}"
          printf 'public-packages=%s\n' "${public_packages}" >>"${GITHUB_OUTPUT}"

          # Determine the new version number and tag name.
          case "${version}" in
            major | minor | patch)
              if [[ ! "${prev_version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                bail "pre-release/build-metadata"
              fi
              major="${prev_version%%.*}"
              minor_patch="${prev_version#*.}"
              minor="${minor_patch%%.*}"
              patch="${minor_patch#*.}"
              case "${version}" in
                major) version="$((major+1)).0.0" ;;
                minor) version="${major}.$((minor+1)).0" ;;
                patch) version="${major}.${minor}.$((patch+1))" ;;
              esac
              ;;
            *) version="${version#v}" ;;
          esac
          if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z\.-]+)?(\+[0-9A-Za-z\.-]+)?$ ]]; then
            bail "invalid version format '${version}'"
          fi
          printf 'version: %s\n' "${version}"
          printf 'version=%s\n' "${version}" >>"${GITHUB_OUTPUT}"
          TAG="${tag_prefix}${version}"
          printf 'tag: %s\n' "${TAG}"
          printf 'tag=%s\n' "${TAG}" >>"${GITHUB_OUTPUT}"

          # Make sure the same release has not been created in the past.
          if gh release view "${TAG}" &>/dev/null; then
            bail "tag '${TAG}' has already been created and pushed"
          fi
          # Make sure that the release was created from an allowed branch.
          if ! git branch | grep -Eq '\* '"${BRANCH}"'$'; then
            bail "current branch is not '${BRANCH}'"
          fi

          changed_paths=()
          retry git fetch origin --tags &>/dev/null
          tags=$(git --no-pager tag | { grep -E "^${tag_prefix}[0-9]+" || true; })
          if [[ -n "${tags}" ]]; then
            printf 'has-tags=true\n' >>"${GITHUB_OUTPUT}"
            # Make sure the same release does not exist in changelog.
            if grep -Eq "^## \\[${version//./\\.}\\]" "${changelog}"; then
              bail "release ${version} already exist in ${changelog}"
            fi
            if grep -Eq "^\\[${version//./\\.}\\]: " "${changelog}"; then
              bail "link to ${version} already exist in ${changelog}"
            fi

            # Update changelog.
            changed_paths+=("${changelog}")
            remote_url=$(grep -E '^\[Unreleased\]: https://' "${changelog}" | sed -E 's/^\[Unreleased\]: //; s/\.\.\.HEAD$//')
            prev_tag="${remote_url#*/compare/}"
            remote_url="${remote_url%/compare/*}"
            sed -Ei \
              -e "s/^## \\[Unreleased\\]/## [Unreleased]\\n\\n## [${version}] - ${release_date}/" \
              -e "s#^\[Unreleased\]: https://.*#[Unreleased]: ${remote_url}/compare/${TAG}...HEAD\\n[${version}]: ${remote_url}/compare/${prev_tag}...${TAG}#" "${changelog}"
            if ! grep -Eq "^## \\[${version//./\\.}\\] - ${release_date}$" "${changelog}"; then
              bail "failed to update ${changelog}"
            fi
            if ! grep -Eq "^\\[${version//./\\.}\\]: " "${changelog}"; then
              bail "failed to update ${changelog}"
            fi
          else
            # Make sure the release exists in changelog.
            if ! grep -Eq "^## \\[${version//./\\.}\\] - ${release_date}$" "${changelog}"; then
              bail "release ${version} does not exist in ${changelog} or has wrong release date"
            fi
            if ! grep -Eq "^\\[${version//./\\.}\\]: " "${changelog}"; then
              bail "link to ${version} does not exist in ${changelog}"
            fi
          fi
          # Make sure that a valid release note for this version exists.
          # https://github.com/taiki-e/parse-changelog
          changes=$(parse-changelog "${changelog}" "${version}")
          if [[ -z "${changes}" ]]; then
            bail "changelog for ${version} has no body"
          fi
          printf '============== CHANGELOG ==============\n'
          printf '%s\n' "${changes}"
          printf '=======================================\n'

          docs=()
          for readme in $(git ls-files '*README.md'); do
            docs+=("${readme}")
            lib="$(dirname -- "${readme}")/src/lib.rs"
            if [[ -f "${lib}" ]]; then
              docs+=("${lib}")
            fi
          done
          changed_paths+=("${docs[@]}")
          while IFS= read -rd, name; do
            manifest_path="${name#*:}"
            name="${name%:*}"
            changed_paths+=("${manifest_path}")
            # Update version in Cargo.toml.
            sed -Ei "s/^version = \"${prev_version}\" #publish:version/version = \"${version}\" #publish:version/g" "${manifest_path}"
            # Update '=' requirement in Cargo.toml.
            for manifest in $(git ls-files '*Cargo.toml'); do
              if grep -Eq "^${name} = \\{ version = \"=${prev_version}\"" "${manifest}"; then
                sed -Ei "s/^${name} = \\{ version = \"=${prev_version}\"/${name} = { version = \"=${version}\"/g" "${manifest}"
                changed_paths+=("${manifest}")
              fi
            done
            # Update version in readme and lib.rs.
            for path in "${docs[@]}"; do
              # TODO: handle pre-release
              if [[ "${version}" == "0.0."* ]]; then
                # 0.0.x -> 0.0.y
                if grep -Eq "^${name} = \"${prev_version}\"" "${path}"; then
                  sed -Ei "s/^${name} = \"${prev_version}\"/${name} = \"${version}\"/g" "${path}"
                fi
                if grep -Eq "^${name} = \\{ version = \"${prev_version}\"" "${path}"; then
                  sed -Ei "s/^${name} = \\{ version = \"${prev_version}\"/${name} = { version = \"${version}\"/g" "${path}"
                fi
              elif [[ "${version}" == "0."* ]]; then
                prev_major_minor="${prev_version%.*}"
                major_minor="${version%.*}"
                if [[ "${prev_major_minor}" != "${major_minor}" ]]; then
                  # 0.x -> 0.y
                  # 0.x.* -> 0.y
                  if grep -Eq "^${name} = \"${prev_major_minor}(\\.[0-9]+)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \"${prev_major_minor}(\\.[0-9]+)?\"/${name} = \"${major_minor}\"/g" "${path}"
                  fi
                  if grep -Eq "^${name} = \\{ version = \"${prev_major_minor}(\\.[0-9]+)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \\{ version = \"${prev_major_minor}(\\.[0-9]+)?\"/${name} = { version = \"${major_minor}\"/g" "${path}"
                  fi
                fi
              else
                prev_major="${prev_version%%.*}"
                major="${version%%.*}"
                if [[ "${prev_major}" != "${major}" ]]; then
                  # x -> y
                  # x.* -> y
                  # x.*.* -> y
                  if grep -Eq "^${name} = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"/${name} = \"${major}\"/g" "${path}"
                  fi
                  if grep -Eq "^${name} = \\{ version = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \\{ version = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"/${name} = { version = \"${major}\"/g" "${path}"
                  fi
                fi
              fi
            done
          done <<<"${public_packages}"

          (
            set -x
            git show HEAD --shortstat
          )

          if [[ -n "${tags}" ]]; then
            (
              set -x
              git -c color.ui=always diff "${changed_paths[@]}"
              git add "${changed_paths[@]}"
              git commit -m "${COMMIT_PREFIX}Release ${version}"
            )
          fi
          # Make sure that there is no unintended change.
          (
            set -x
            git add -N .
            git -c color.ui=always diff --exit-code
          )

          (
            set -x
            git tag "${TAG}"
          )

          args=''
          if [[ -n "${INPUT_TARGET}" ]]; then
            args+="--target,${INPUT_TARGET},"
          fi
          if [[ -n "${INPUT_PACKAGE}" ]]; then
            package=$(normalize_comma_or_space_separated "${INPUT_PACKAGE}")
            if [[ -n "${package}" ]]; then
              while IFS= read -rd,; do
                args+="-p,${REPLY},"
              done <<<"${package}"
            fi
          fi
          if [[ "${INPUT_WORKSPACE}" == 'true' ]]; then
            args+='--workspace,'
          fi
          if [[ -n "${INPUT_ARGS}" ]]; then
            while IFS= read -rd' '; do
              [[ -z "${REPLY}" ]] || args+="${REPLY},"
            done <<<"${INPUT_ARGS//[$'\r\n\t']/ } " # Normalize whitespace characters into space.
          fi
          printf 'args=%s\n' "${args}" >>"${GITHUB_OUTPUT}"

          if [[ -n "${BIN}" ]]; then
            if [[ -z "${BIN_TARGET}" ]]; then
              bail "'bin' input option may only be used together with 'bin-target' input option"
            fi
            matrix=''
            while IFS= read -rd, target; do
              matrix+=',{"target":"'"${target}"'","os":"'
              case "${target}" in
                *-linux-gnu*) matrix+=ubuntu-22.04 ;;
                *-apple-*) matrix+=macos-15 ;;
                *-windows-*) matrix+=windows-2022 ;;
                *) matrix+=ubuntu-24.04 ;;
              esac
              matrix+='"}'
            done < <(normalize_comma_or_space_separated "${BIN_TARGET}")
            printf 'matrix=%s\n' "{\"include\":[${matrix#,}]}" >>"${GITHUB_OUTPUT}"
          elif [[ -n "${BIN_TARGET}" ]]; then
            bail "'bin-target' input option may only be used together with 'bin' input option"
          fi
        env:
          VERSION: ${{ inputs.version }}
          TAG_PREFIX: ${{ inputs.tag-prefix }}
          CHANGELOG: ${{ inputs.changelog }}
          BRANCH: ${{ inputs.branch }}
          COMMIT_PREFIX: ${{ inputs.commit-prefix }}
          INPUT_TARGET: ${{ inputs.target }}
          INPUT_PACKAGE: ${{ inputs.package }}
          INPUT_WORKSPACE: ${{ inputs.workspace }}
          INPUT_ARGS: ${{ inputs.args }}
          BIN: ${{ inputs.bin }}
          BIN_TARGET: ${{ inputs.bin-target }}
      - name: Build crates to be published
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          args=()
          if [[ -n "${INPUT_ARGS}" ]]; then
            while IFS= read -rd,; do
              args+=("${REPLY}")
            done <<<"${INPUT_ARGS}"
          fi
          (
            set -x
            cargo publish --dry-run "${args[@]}"
          )
        env:
          INPUT_ARGS: ${{ steps.check.outputs.args }}
    outputs:
      has-tags: ${{ steps.check.outputs.has-tags }}
      release-date: ${{ steps.check.outputs.release-date }}
      rev: ${{ steps.check.outputs.rev }}
      tag: ${{ steps.check.outputs.tag }}
      version: ${{ steps.check.outputs.version }}
      prev-version: ${{ steps.check.outputs.prev-version }}
      public-packages: ${{ steps.check.outputs.public-packages }}
      args: ${{ steps.check.outputs.args }}
      matrix: ${{ steps.check.outputs.matrix }}

  release:
    needs: prepare
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    environment:
      name: release
      deployment: false
    permissions:
      contents: write # for taiki-e/create-gh-release-action
      id-token: write # for rust-lang/crates-io-auth-action
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/install-action@b8cecb83565409bcc297b2df6e77f030b2a468d5 # v2.82.0
        with:
          tool: rust@${{ inputs.rust }}+${{ inputs.target }},parse-changelog
          fallback: none
      - name: Create commit and tag
        id: commit
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          bail() {
            printf '::error::%s\n' "$*"
            exit 1
          }

          git() { command git -c core.fsmonitor=false "$@"; }
          git config user.name 'Taiki Endo'
          git config user.email 'te316e89@gmail.com'

          # shellcheck disable=SC2153
          version="${VERSION}"
          # shellcheck disable=SC2153
          prev_version="${PREV_VERSION}"
          # shellcheck disable=SC2153
          changelog="${CHANGELOG}"
          # shellcheck disable=SC2153
          release_date="${RELEASE_DATE}"

          # Make sure the current revision is same as prepare step.
          rev=$(git rev-parse HEAD)
          if [[ "${rev}" != "${PREPARE_REV}" ]]; then
            bail "revision difference between prepare step"
          fi

          # Make sure the same release has not been created in the past.
          if gh release view "${TAG}" &>/dev/null; then
            bail "tag '${TAG}' has already been created and pushed"
          fi
          # Make sure that the release was created from an allowed branch.
          if ! git branch | grep -Eq '\* '"${BRANCH}"'$'; then
            bail "current branch is not '${BRANCH}'"
          fi

          changed_paths=()
          if [[ "${HAS_TAGS}" == "true" ]]; then
            # Update changelog.
            changed_paths+=("${changelog}")
            remote_url=$(grep -E '^\[Unreleased\]: https://' "${changelog}" | sed -E 's/^\[Unreleased\]: //; s/\.\.\.HEAD$//')
            prev_tag="${remote_url#*/compare/}"
            remote_url="${remote_url%/compare/*}"
            sed -Ei \
              -e "s/^## \\[Unreleased\\]/## [Unreleased]\\n\\n## [${version}] - ${release_date}/" \
              -e "s#^\[Unreleased\]: https://.*#[Unreleased]: ${remote_url}/compare/${TAG}...HEAD\\n[${version}]: ${remote_url}/compare/${prev_tag}...${TAG}#" "${changelog}"
            if ! grep -Eq "^## \\[${version//./\\.}\\] - ${release_date}$" "${changelog}"; then
              bail "failed to update ${changelog}"
            fi
            if ! grep -Eq "^\\[${version//./\\.}\\]: " "${changelog}"; then
              bail "failed to update ${changelog}"
            fi
          fi
          changes=$(parse-changelog "${changelog}" "${version}")
          printf '============== CHANGELOG ==============\n'
          printf '%s\n' "${changes}"
          printf '=======================================\n'

          docs=()
          for readme in $(git ls-files '*README.md'); do
            docs+=("${readme}")
            lib="$(dirname -- "${readme}")/src/lib.rs"
            if [[ -f "${lib}" ]]; then
              docs+=("${lib}")
            fi
          done
          changed_paths+=("${docs[@]}")
          while IFS= read -rd, name; do
            manifest_path="${name#*:}"
            name="${name%:*}"
            changed_paths+=("${manifest_path}")
            # Update version in Cargo.toml.
            sed -Ei "s/^version = \"${prev_version}\" #publish:version/version = \"${version}\" #publish:version/g" "${manifest_path}"
            # Update '=' requirement in Cargo.toml.
            for manifest in $(git ls-files '*Cargo.toml'); do
              if grep -Eq "^${name} = \\{ version = \"=${prev_version}\"" "${manifest}"; then
                sed -Ei "s/^${name} = \\{ version = \"=${prev_version}\"/${name} = { version = \"=${version}\"/g" "${manifest}"
                changed_paths+=("${manifest}")
              fi
            done
            # Update version in readme and lib.rs.
            for path in "${docs[@]}"; do
              # TODO: handle pre-release
              if [[ "${version}" == "0.0."* ]]; then
                # 0.0.x -> 0.0.y
                if grep -Eq "^${name} = \"${prev_version}\"" "${path}"; then
                  sed -Ei "s/^${name} = \"${prev_version}\"/${name} = \"${version}\"/g" "${path}"
                fi
                if grep -Eq "^${name} = \\{ version = \"${prev_version}\"" "${path}"; then
                  sed -Ei "s/^${name} = \\{ version = \"${prev_version}\"/${name} = { version = \"${version}\"/g" "${path}"
                fi
              elif [[ "${version}" == "0."* ]]; then
                prev_major_minor="${prev_version%.*}"
                major_minor="${version%.*}"
                if [[ "${prev_major_minor}" != "${major_minor}" ]]; then
                  # 0.x -> 0.y
                  # 0.x.* -> 0.y
                  if grep -Eq "^${name} = \"${prev_major_minor}(\\.[0-9]+)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \"${prev_major_minor}(\\.[0-9]+)?\"/${name} = \"${major_minor}\"/g" "${path}"
                  fi
                  if grep -Eq "^${name} = \\{ version = \"${prev_major_minor}(\\.[0-9]+)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \\{ version = \"${prev_major_minor}(\\.[0-9]+)?\"/${name} = { version = \"${major_minor}\"/g" "${path}"
                  fi
                fi
              else
                prev_major="${prev_version%%.*}"
                major="${version%%.*}"
                if [[ "${prev_major}" != "${major}" ]]; then
                  # x -> y
                  # x.* -> y
                  # x.*.* -> y
                  if grep -Eq "^${name} = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"/${name} = \"${major}\"/g" "${path}"
                  fi
                  if grep -Eq "^${name} = \\{ version = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"" "${path}"; then
                    sed -Ei "s/^${name} = \\{ version = \"${prev_major}(\\.[0-9]+(\\.[0-9]+)?)?\"/${name} = { version = \"${major}\"/g" "${path}"
                  fi
                fi
              fi
            done
          done <<<"${PUBLIC_PACKAGES}"

          if [[ "${HAS_TAGS}" == "true" ]]; then
            # Create a release commit.
            (
              set -x
              git add "${changed_paths[@]}"
              git commit -m "${COMMIT_PREFIX}Release ${version}"
            )
          fi
          rev=$(git rev-parse HEAD)
          printf 'rev: %s\n' "${rev}"
          printf 'rev=%s\n' "${rev}" >>"${GITHUB_OUTPUT}"

          (
            set -x
            git tag "${TAG}"
          )
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
          PREV_VERSION: ${{ needs.prepare.outputs.prev-version }}
          PUBLIC_PACKAGES: ${{ needs.prepare.outputs.public-packages }}
          RELEASE_DATE: ${{ needs.prepare.outputs.release-date }}
          HAS_TAGS: ${{ needs.prepare.outputs.has-tags }}
          TAG: ${{ needs.prepare.outputs.tag }}
          CHANGELOG: ${{ inputs.changelog }}
          BRANCH: ${{ inputs.branch }}
          COMMIT_PREFIX: ${{ inputs.commit-prefix }}
          PREPARE_REV: ${{ needs.prepare.outputs.rev }}
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: push-token
        with:
          client-id: ${{ secrets.PUSH_TOKEN_APP_CLIENT_ID }}
          private-key: ${{ secrets.PUSH_TOKEN_APP_PRIVATE_KEY }}
      - uses: taiki-e/github-actions/push@daf550b807efeb6fcd612a0743fe0803f313f4aa # main # zizmor: ignore[stale-action-refs]
        with:
          ref: HEAD,refs/tags/${{ needs.prepare.outputs.tag }}
          # Note that if we use secrets.GITHUB_TOKEN, the pushed commit/tag cannot trigger other workflows.
          # Also, updating these refs is disallowed for secrets.GITHUB_TOKEN by ruleset.
          token: ${{ steps.push-token.outputs.token }}
      - uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651 # v1.11.0
        with:
          changelog: ${{ inputs.changelog }}
          title: ${{ inputs.title }}
          branch: ${{ inputs.branch }}
          prefix: ${{ inputs.prefix }}
          draft: true
          ref: refs/tags/${{ needs.prepare.outputs.tag }}
      - uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
        id: auth
        if: needs.prepare.outputs.has-tags == 'true'
      - name: Publish to crates.io
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          args=()
          if [[ -n "${INPUT_ARGS}" ]]; then
            while IFS= read -rd,; do
              args+=("${REPLY}")
            done <<<"${INPUT_ARGS}"
          fi
          # TODO: retry on failure
          (
            set -x
            cargo publish --no-verify "${args[@]}"
          )
        env:
          CARGO_REGISTRY_TOKEN: ${{ needs.prepare.outputs.has-tags == 'true' && steps.auth.outputs.token || secrets.CARGO_REGISTRY_TOKEN }}
          INPUT_ARGS: ${{ needs.prepare.outputs.args }}
      - run: gh release edit "${TAG}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.prepare.outputs.tag }}
        if: inputs.bin == ''
    outputs:
      rev: ${{ steps.commit.outputs.rev }}

  upload-assets:
    name: upload-assets ${{ matrix.target }}
    if: inputs.bin != ''
    needs: [prepare, release]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: write # for taiki-e/upload-rust-binary-action
      id-token: write # for actions/attest
      attestations: write # for actions/attest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      # TODO: Use checkout-action's option once https://github.com/taiki-e/checkout-action/issues/3 implemented.
      - run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          bail() {
            printf '::error::%s\n' "$*"
            exit 1
          }

          git() { command git -c core.fsmonitor=false "$@"; }

          retry git fetch origin --tags &>/dev/null
          git checkout "${REF}"
          # Make sure the current revision is same as release step.
          rev=$(git rev-parse HEAD)
          if [[ "${rev}" != "${RELEASE_REV}" ]]; then
            bail "revision difference between release step"
          fi
        env:
          REF: refs/tags/${{ needs.prepare.outputs.tag }}
          RELEASE_REV: ${{ needs.release.outputs.rev }}
      - uses: taiki-e/install-action@b8cecb83565409bcc297b2df6e77f030b2a468d5 # v2.82.0
        with:
          tool: rust@${{ inputs.rust }}
          fallback: none
      - uses: taiki-e/setup-cross-toolchain-action@3d9770ce98eb7dbcf378563182a5e8031165f75b # v1.41.0
        with:
          target: ${{ matrix.target }}
          runner: none
      - run: printf 'RUSTFLAGS=%s\n' "${RUSTFLAGS} -C target-feature=+crt-static" >>"${GITHUB_ENV}"
        if: contains(matrix.target, '-windows-msvc')
      - run: printf 'RUSTFLAGS=%s\n' "${RUSTFLAGS} -C target-feature=+crt-static -C link-self-contained=yes" >>"${GITHUB_ENV}"
        if: contains(matrix.target, '-linux-musl')
      # https://doc.rust-lang.org/rustc/platform-support.html
      - run: printf 'MACOSX_DEPLOYMENT_TARGET=10.12\n' >>"${GITHUB_ENV}"
        if: matrix.target == 'x86_64-apple-darwin'
      - run: printf 'MACOSX_DEPLOYMENT_TARGET=11.0\n' >>"${GITHUB_ENV}"
        if: matrix.target == 'aarch64-apple-darwin' || matrix.target == 'universal-apple-darwin'
      - id: upload
        uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6 # v1.30.2
        with:
          bin: ${{ inputs.bin }}
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          ref: refs/tags/${{ needs.prepare.outputs.tag }}
      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: ${{ steps.upload.outputs.archive }}.*

  github-release:
    if: inputs.bin != ''
    needs: [prepare, release, upload-assets]
    runs-on: ubuntu-slim
    timeout-minutes: 15 # Max execution time of ubuntu-slim runner.
    permissions:
      contents: write # for gh release edit
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - run: gh release edit "${REF#refs/tags/}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: refs/tags/${{ needs.prepare.outputs.tag }}
