# Run various checks.
#
# There is no stability guarantee for this workflow, since it's supposed to only be
# used in infra managed by us.
#
# Usage:
#
# ```yaml
#   tidy:
#     uses: taiki-e/github-actions/.github/workflows/tidy.yml@main
#     permissions:
#       contents: write # for creating branch for pr
#       pull-requests: write # unused (used in `codegen-automerge: true` case)
#       security-events: write # for github/codeql-action/*
#     secrets:
#       PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
# ```
#
# See "on.workflow_call.inputs" below for input options.

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      rust:
        required: false
        type: string
        default: nightly
      clippy:
        required: false
        type: boolean
        default: true
      clippy-target:
        required: false
        type: string
      clippy-args:
        required: false
        type: string
      clippy-doctest:
        required: false
        type: boolean
        default: true
      unqualified_local_imports:
        required: false
        type: boolean
        default: true
      fuzzy_provenance_casts:
        required: false
        type: boolean
        default: true
      check-external-types:
        required: false
        type: boolean
        default: true
      check-external-types-rust:
        required: false
        type: string
        default: nightly-2025-10-18
      check-external-types-target:
        required: false
        type: string
      check-external-types-args:
        required: false
        type: string
      deny:
        required: false
        type: boolean
        default: true
      deny-args:
        required: false
        type: string
      docs:
        required: false
        type: boolean
        default: true
      docs-target:
        required: false
        type: string
      docs-args:
        required: false
        type: string
      codeql:
        required: false
        type: boolean
        default: true
      codegen:
        required: false
        type: boolean
        default: true
      codegen-automerge:
        required: false
        type: boolean
        default: false
      codegen-free-device-space:
        required: false
        type: boolean
        default: false
      codegen-workflow:
        required: false
        type: string
        default: .github/workflows/ci.yml
      codegen-job:
        required: false
        type: string
        default: codegen
      immutable-release:
        required: false
        type: boolean
        default: true
      pr-token-app-client-id:
        required: false
        type: string
        default: Iv23liTXn5nJSj4JzqMb # https://github.com/apps/taiki-e-automated-pr
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY:
        required: false

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  # Reusable workflows cannot inherit environment variables.
  ATOMIC_MAYBE_UNINIT_DENY_WARNINGS: 1
  CARGO_HACK_DENY_WARNINGS: 1
  CARGO_LLVM_COV_DENY_WARNINGS: 1
  CARGO_MINIMAL_VERSIONS_DENY_WARNINGS: 1
  CARGO_NO_DEV_DEPS_DENY_WARNINGS: 1
  CONST_FN_DENY_WARNINGS: 1
  PORTABLE_ATOMIC_DENY_WARNINGS: 1
  SEMIHOSTING_DENY_WARNINGS: 1

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  prepare:
    runs-on: ubuntu-slim
    timeout-minutes: 15 # Max execution time of ubuntu-slim runner.
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - name: Prepare
        id: prepare
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          python3 -m venv ~/venv
          ~/venv/bin/pip --version
          # --uploaded-prior-to requires pip 26.0.
          ~/venv/bin/pip install --upgrade pip
          ~/venv/bin/pip install --uploaded-prior-to="$(date -d '-14days' -Idate)" yq
          yq() { ~/venv/bin/yq "$@"; }
          if [[ -n "$(git ls-files '*.rs')" ]]; then
            printf 'rust=true\n' >>"${GITHUB_OUTPUT}"
            if ! type -P rustup; then
              retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 -o rustup-init https://sh.rustup.rs
              chmod +x ./rustup-init
              retry ./rustup-init -y --default-toolchain "${INPUT_RUST}" --no-modify-path --profile minimal
              rm -- ./rustup-init
              export PATH="${HOME}/.cargo/bin:${PATH}"
            fi
            metadata=$(cargo metadata --format-version=1 --no-deps)
            # Publishing is unrestricted if null, and forbidden if an empty array.
            if [[ -n "$(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [])' <<<"${metadata}")" ]]; then
              printf 'rust-pub=true\n' >>"${GITHUB_OUTPUT}"
              if [[ -n "$(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [] and .targets[].kind[] == "lib")' <<<"${metadata}")" ]]; then
                printf 'rust-pub-lib=true\n' >>"${GITHUB_OUTPUT}"
              fi
              if [[ -n "$(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [] and .targets[].kind[] == "proc-macro")' <<<"${metadata}")" ]]; then
                printf 'rust-pub-proc-macro=true\n' >>"${GITHUB_OUTPUT}"
              fi
            fi
          fi
          if [[ -n "$(git ls-files '*Dockerfile*')" ]]; then
            printf 'dockerfile=true\n' >>"${GITHUB_OUTPUT}"
          fi
          if [[ -e tools/gen.sh ]]; then
            job=$(yq -c ".jobs.\"${INPUT_CODEGEN_JOB}\"" "${INPUT_CODEGEN_WORKFLOW}")
            if [[ "${job}" == "null" ]]; then
              printf 'codegen=true\n' >>"${GITHUB_OUTPUT}"
            fi
          elif [[ -e tools/ci/gen.sh ]]; then
            printf '%s\n' "::error::tools/ci/gen.sh is available but tools/gen.sh is not available"
            exit 1
          fi
        env:
          INPUT_RUST: ${{ inputs.rust }}
          INPUT_CODEGEN_JOB: ${{ inputs.codegen-job }}
          INPUT_CODEGEN_WORKFLOW: ${{ inputs.codegen-workflow }}
    outputs:
      rust: ${{ steps.prepare.outputs.rust }}
      rust-pub: ${{ steps.prepare.outputs.rust-pub }}
      rust-pub-lib: ${{ steps.prepare.outputs.rust-pub-lib }}
      rust-pub-proc-macro: ${{ steps.prepare.outputs.rust-pub-proc-macro }}
      dockerfile: ${{ steps.prepare.outputs.dockerfile }}
      codegen: ${{ steps.prepare.outputs.codegen }}

  tidy:
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write # for creating branch for pr
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - run: cat -- tools/.tidy-check-license-headers
      - run: cat -- .cspell.json
      - run: printf 'REMOVE_UNUSED_WORDS=1\n' >>"${GITHUB_ENV}"
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main')
      - run: tools/tidy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check ruleset
        id: ruleset
        run: |
          set +x
          IFS=$'\n\t'
          bail() {
            printf '::error::%s\n' "$*"
            exit 1
          }
          ruleset=$(gh ruleset list)
          check() {
            local name="$1"
            shift
            local min_rules="$1"
            shift
            local output="$1"
            shift
            local rule_id
            rule_id=$(grep -E "${name}"'\b.*\bactive\b.*\b(['"${min_rules}"'-9]|[1-9][0-9])' <<<"${ruleset}" | cut -d$'\t' -f1)
            printf '%s=%s\n' "${output}" "${rule_id}" >>"${GITHUB_OUTPUT}"
            rule=$(gh ruleset view "${rule_id}")
            printf '%s\n' "${rule}"
            for r in "$@"; do
              grep -Eq "${r}" <<<"${rule}" || bail "ruleset check failed for '${name}' (missing '${r}')"
            done
          }
          check 'Additional branch protection for non-admin roles' 4 'branch-additional' \
            '^- code_scanning: ' \
            '^- non_fast_forward$' \
            '^- pull_request: .*\[required_approving_review_count: ([1-9]|[1-9][0-9])\]' \
            '^- pull_request: .*\[dismiss_stale_reviews_on_push: true\]' \
            '^- pull_request: .*\[allowed_merge_methods: \[squash rebase\]\]' \
            '^- required_status_checks: '
          check 'Additional tag protection for non-admin roles' 4 'tag-additional' \
            '^- ref_name: \[exclude: \[\]\] \[include: \[~ALL\]\]' \
            '^- creation$' \
            '^- deletion$' \
            '^- non_fast_forward$' \
            '^- update$'
          check 'Branch protection for all roles' 2 'branch' \
            '^This ruleset cannot be bypassed$' \
            '^- deletion$' \
            '^- non_fast_forward$'
          check 'Tag protection for all roles' 3 'tag' \
            '^This ruleset cannot be bypassed$' \
            '^- deletion$' \
            '^- non_fast_forward$' \
            '^- update$'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main')
      - name: Ensure all tags are contained in protected branches
        run: |
          IFS=$'\n\t'
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                set -x
                sleep "${i}"
              fi
            done
            "$@"
          }
          retry git fetch origin --tags &>/dev/null
          set +x
          tags=$(git tag | sort -Vr)
          if [[ -z "${tags}" ]]; then
            exit 0
          fi
          all_branches=$(git branch -a | grep -F 'remotes/origin/' | { grep -Fv -e '->' || true; } | sed -E 's|^ *remotes/origin/||g')
          protected_branches=()
          while IFS='' read -r branch; do
            rule=$(gh ruleset check "${branch}")
            if grep -Fq "${RULE_ID1}" <<<"${rule}" || grep -Fq "${RULE_ID2}" <<<"${rule}"; then
              protected_branches+=("${branch}")
            fi
          done <<<"${all_branches}"
          IFS=' '
          printf 'info: protected branches: %s\n' "${protected_branches[*]}"
          IFS=$'\n\t'
          rate_limit=''
          while IFS='' read -r tag; do
            printf 'info: checking %s...\n' "${tag}"
            # Refs: https://github.com/zizmorcore/zizmor/blob/v1.23.1/crates/zizmor/src/audit/impostor_commit.rs
            commit=$(git show refs/tags/"${tag}" --name-only --no-color | grep -E '^commit' | cut -d' ' -f2)
            ok=''
            code=''
            if [[ -z "${rate_limit}" ]]; then
              set +e
              res=$(
                curl --proto '=https' -fsSL \
                  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                  -H 'Accept: application/json' \
                  "https://github.com/${GITHUB_REPOSITORY}/branch_commits/${commit}" 2>&1
              )
              code="$?"
              set -e
              set +x
            fi
            if [[ "${code}" == "0" ]]; then
              if [[ -z "${res}" ]]; then
                # TODO: collect all and emit at the last?
                printf '%s\n' "::error::${tag} is not contained in any branches"
                exit 1
              fi
              branches="$(jq -r '.branches[] | .branch' <<<"${res}")"
              if [[ -z "${branches}" ]]; then
                printf '%s\n' "::error::${tag} is not contained in any branches"
                exit 1
              fi
              while IFS='' read -r branch; do
                for b in "${protected_branches[@]}"; do
                  if [[ "${branch}" == "${b}" ]]; then
                    ok=1
                    break
                  fi
                done
                if [[ -n "${ok}" ]]; then
                  break
                fi
              done <<<"${branches}"
            else
              if [[ -n "${code}" ]] && [[ "${res}" == *"returned error: 429"* ]]; then
                # branch_commits API hits its rate limit after fetching 100 commits.
                rate_limit=1
              fi
              similar_name_branches=()
              other_branches=()
              for branch in "${protected_branches[@]}"; do
                if [[ "main" == "${branch}" ]] || [[ "${branch#*/}" == *"${tag#*/}"* ]] || [[ "${tag#*/}" == *"${branch#*/}"* ]]; then
                  similar_name_branches+=("${branch}")
                else
                  other_branches+=("${branch}")
                fi
              done
              for branch in "${similar_name_branches[@]}" "${other_branches[@]}"; do
                url="https://api.github.com/repos/${GITHUB_REPOSITORY}/compare/refs/heads/${branch}...${commit}"
                for i in {1..10}; do
                  if [[ "${i}" == '2' ]]; then
                    printf 'info: getting %s\n' "${url}"
                  fi
                  set +e
                  cmp=$(
                    curl --proto '=https' --tlsv1.2 --fail-with-body -sSL \
                      -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                      -H 'Accept: application/vnd.github+json' \
                      -H 'X-GitHub-Api-Version: 2022-11-28' \
                      "${url}"
                  )
                  code="$?"
                  set -e
                  if [[ "${code}" == '0' ]]; then
                    break
                  elif [[ "$(jq -r '.documentation_url' <<<"${cmp}")" != "null" ]] && [[ "$(jq -r '.status' <<<"${cmp}")" == "404" ]]; then
                    break
                  else
                    sleep "${i}"
                  fi
                done
                case "$(jq -r '.status' <<<"${cmp}")" in
                  identical | behind)
                    ok=1
                    break
                    ;;
                esac
              done
            fi
            if [[ -z "${ok}" ]]; then
              printf '%s\n' "::error::${tag} is not contained in any protected branches"
              exit 1
            fi
            printf 'info: done\n'
          done <<<"${tags}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RULE_ID1: ${{ steps.ruleset.outputs.branch-additional }}
          RULE_ID2: ${{ steps.ruleset.outputs.branch }}
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main')
      - name: Ensure all releases are immutable
        run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          set +x
          page=1
          not_immutable=''
          while true; do
            releases=$(
              retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 \
                -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                -H 'Accept: application/vnd.github+json' \
                -H 'X-GitHub-Api-Version: 2022-11-28' \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases?per_page=100&page=${page}"
            )
            t=$(jq -r '.[] | select(.immutable == false and .draft == false) | .tag_name' <<<"${releases}")
            if [[ -n "${t}" ]]; then
              not_immutable+="${t}"$'\n'
            fi
            len=$(jq '. | length' <<<"${releases}")
            if [[ "${len}" -lt 100 ]]; then
              break
            fi
            _=$((page++))
          done
          if [[ -n "${not_immutable}" ]]; then
            printf '%s\n' "::error::non-immutable releases found"
            LC_ALL=C sort -Vr <<<"${not_immutable}"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: inputs.immutable-release && github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main')
      - run: |
          [[ ! -f tools/cspell-dict.sh ]] || {
            # min-release-age and allow-git requires npm 11.10+
            npm --version
            sudo npm install --location=global npm@11.11.0
            tools/cspell-dict.sh clean
          }
      - name: Handle diff
        id: diff
        run: |
          git config user.name 'Taiki Endo'
          git config user.email 'te316e89@gmail.com'
          git add -N .github/.cspell
          if ! git diff --exit-code -- .github/.cspell &>/dev/null; then
            git add .github/.cspell
            git commit -m "Update cspell dictionary"
            printf 'success=false\n' >>"${GITHUB_OUTPUT}"
          fi
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main')
      - run: git add -N . && git -c color.ui=always diff --exit-code
      - uses: taiki-e/github-actions/push@d34e3b863da529f7c30e571fec0170fbf64fa40c # main # zizmor: ignore[stale-action-refs]
        with:
          ref: refs/heads/update-cspell-dictionary
          force: true
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main') && steps.diff.outputs.success == 'false'
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: pr-token
        with:
          client-id: ${{ inputs.pr-token-app-client-id }}
          private-key: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }} # zizmor: ignore[secrets-outside-env] # TODO
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main') && steps.diff.outputs.success == 'false'
      - name: Create or re-open PR
        run: |
          if ! gh pr create --title "${TITLE:?}" --body "${BODY}" 2>&1 | tee -- /tmp/create.log; then
            if grep -Eq 'pull request for branch ".*" into branch ".*" already exists' /tmp/create.log; then
              # close and re-open if already exists because token used to push cannot trigger workflow
              gh pr close "${BRANCH:?}"
              gh pr reopen "${BRANCH}"
            else
              exit 1
            fi
          fi
          rm -- /tmp/create.log
        env:
          TITLE: Update cspell dictionary
          BODY: |
            Auto-generated by CI.
          BRANCH: update-cspell-dictionary
          # Note that if we use secrets.GITHUB_TOKEN, the opened PR cannot trigger workflows.
          GITHUB_TOKEN: ${{ steps.pr-token.outputs.token }} # zizmor: ignore[secrets-outside-env] # TODO
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main') && steps.diff.outputs.success == 'false'

  check-external-types:
    needs: prepare
    if: inputs.check-external-types && needs.prepare.outputs.rust-pub-lib == 'true'
    uses: ./.github/workflows/check-external-types.yml
    with:
      rust: ${{ inputs.check-external-types-rust }}
      target: ${{ inputs.check-external-types-target }}
      args: ${{ inputs.check-external-types-args }}

  clippy:
    needs: prepare
    if: inputs.clippy && needs.prepare.outputs.rust == 'true'
    uses: ./.github/workflows/clippy.yml
    with:
      rust: ${{ inputs.rust }}
      target: ${{ inputs.clippy-target }}
      args: ${{ inputs.clippy-args }}
      doctest: ${{ inputs.clippy-doctest }}
      unqualified_local_imports: ${{ inputs.unqualified_local_imports }}
      fuzzy_provenance_casts: ${{ inputs.fuzzy_provenance_casts }}

  codeql:
    needs: prepare
    if: inputs.codeql
    uses: ./.github/workflows/codeql.yml
    permissions:
      contents: read
      security-events: write # for github/codeql-action/*
    with:
      rust: ${{ inputs.rust }}

  codegen:
    needs: prepare
    if: inputs.codegen && needs.prepare.outputs.codegen == 'true'
    uses: ./.github/workflows/gen.yml
    permissions:
      contents: write # for creating branch for pr
      pull-requests: write # for gh pr review --approve
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
    with:
      automerge: ${{ inputs.codegen-automerge }}
      free-device-space: ${{ inputs.codegen-free-device-space }}
      install-rust: ${{ needs.prepare.outputs.rust == 'true' }}
      pr-token-app-client-id: ${{ inputs.pr-token-app-client-id }}

  deny:
    needs: prepare
    if: inputs.deny && needs.prepare.outputs.rust-pub == 'true'
    uses: ./.github/workflows/deny.yml
    with:
      rust: ${{ inputs.rust }}
      args: ${{ inputs.deny-args }}

  docs:
    needs: prepare
    if: inputs.docs && (needs.prepare.outputs.rust-pub-lib == 'true' || needs.prepare.outputs.rust-pub-proc-macro == 'true')
    uses: ./.github/workflows/docs.yml
    with:
      rust: ${{ inputs.rust }}
      target: ${{ inputs.docs-target }}
      args: ${{ inputs.docs-args }}
